services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=arquivo
      - MYSQL_ROOT_PASSWORD=mysecret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: